### ISSUE TITLE
Issue with pull data using wasptool --pull command

### ISSUE THREAD

**Issue by Pittconnect** [daniel-thompson/wasp-os#220]
![image](https://user-images.githubusercontent.com/30482556/122399714-0d70f180-cf49-11eb-8b07-1e747e58c7a2.png)

**Comment by Pittconnect** [comment]
pi@raspberrypi:~/616/wasp-os $ ./tools/wasptool --upload wasp/main.py
Uploading wasp/main.py:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/wasptool", line 425, in <module>
    handle_upload(console, args.upload, args.upload_as)
  File "./tools/wasptool", line 323, in handle_upload
    c.expect('=== ')
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7632fcf0>
command: ./tools/pynus/pynus.py
args: [b'./tools/pynus/pynus.py']
buffer (last 100 chars): 'upload("main.py")\r\r\nMemoryError: memory allocation failed, allocating 512 bytes\r\r\n>>> '
before (last 100 chars): 'upload("main.py")\r\r\nMemoryError: memory allocation failed, allocating 512 bytes\r\r\n>>> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 13992
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('=== ')
pi@raspberrypi:~/616/wasp-os $

**Comment by Pittconnect** [comment]
![image](https://user-images.githubusercontent.com/30482556/122637065-a2472c80-d0ba-11eb-8d15-8abf1c1b7474.png)
OK the pull command does work it is just there is no hrs.data file created by default has anybody see hrs.data file created when the ppg app is running ?

**Comment by Pittconnect** [comment]
Ok After June 19th it started working automatically 
![image](https://user-images.githubusercontent.com/30482556/122664233-30301f80-d16e-11eb-9ddf-ca5762443119.png)
